### ISSUE TITLE
Cant Connect Servers[Fixed]

### ISSUE THREAD

**Issue by KillergameReal** [Foreheadchann/ViaMCP-Reborn#11]
I cant Connect Server This Message Is Showing up After i change my Protocol:
Java.nio.channels.closedChanellExeption

and when i try log with 1.12.2 (Main Protocol)

My game just gona Crash !

Please Help !

**Comment by Foreheadchann** [comment]
please contant me on discord about this so i can help fix it more easily: Hideri#9003
