### ISSUE TITLE
Cant send some 1.9+ only packets with a 1.8 base..

### ISSUE THREAD

**Issue by null-swap** [Foreheadchann/ViaMCP-Reborn#21]
not really a issue but i would like to find out how to send teleport confirmation packets which you can do on a 1.9+ base...

**Comment by Foreheadchann** [comment]
Teleport confirm packets are server-bound, how do you think you are going to send them?

**Comment by null-swap** [comment]
I can just do something like CPacketConfirmTeleport atleast i remember that in 1.12...

**Comment by Foreheadchann** [comment]
Also ViaMCP isnt a version changer, its a version spoofer, its not meant to do tasks that different versions have, like 1.9+ cooldown system

**Comment by Foreheadchann** [comment]
Closing due to nothing more to explain for this thread
