### ISSUE TITLE
Doesn't work on some servers

### ISSUE THREAD

**Issue by EclipseAFK** [Foreheadchann/ViaMCP-Reborn#24]
![image](https://user-images.githubusercontent.com/60032874/153002486-b7cedf8f-cabf-46e0-9fba-d3f984c77eb9.png)
IP: mc.reallyworld.ru
Needed protocol: 1.16
Main protocol: 1.12.2

**Comment by Foreheadchann** [comment]
ViaVersion issue

**Comment by EclipseAFK** [comment]
It can be fixed with some tricks, idk how

**Comment by Foreheadchann** [comment]
You would need to experiment with packets and minecrafts code more than needed, so i am not going to go add specific fixes myself
