### ISSUE TITLE
When 1.18 version?

### ISSUE THREAD

**Issue by alex-s168** [Foreheadchann/ViaMCP-Reborn#30]
will there ever be a 1.18 version? when?

**Comment by hiderikzki** [comment]
sorry for the late response, as of now I do not have a specific date to adapt this to above 1.12.x, but it is possible that it will come out before the end of the summer months, or if i figure out how the newer gui system works, as mojang made it extremely annoying to work with. (this will be re:opened if i have any updates or proper progress made)
