### ISSUE TITLE
Problems with EnumChatFormatting

### ISSUE THREAD

**Issue by NaNonnI** [Foreheadchann/ViaMCP-Reborn#5]
in GuiProtocolSelector in viamcp.gui

EnumChatFormating is replaced with TextFormatting in 1.12.2

EnumChatFormating.BOLD > TextFormatting.BOLD
etc..
import net.minecraft.util.EnumChatFormating; > import net.minecraft.util.text.TextFormatting;

And now there is problems with drawSlot
![image](https://user-images.githubusercontent.com/42698703/124917098-b44e2800-dff3-11eb-8738-80c35b023071.png)

And in
![image](https://user-images.githubusercontent.com/42698703/124917108-badc9f80-dff3-11eb-9131-84a22c161325.png)

Thanks

**Comment by Foreheadchann** [comment]
This was meant for 1.8.x clients, i may port this to 1.12.2 sooner or later tho

**Comment by Foreheadchann** [comment]
Added a 1.12.2 Patch, Decided not to be lazy, tested and is working!
Have a good day :)
