### ISSUE TITLE
Packets Errors

### ISSUE THREAD

**Issue by Godwhitelight** [Foreheadchann/ViaMCP-Reborn#7]
![java_zXtbXjbOrj](https://user-images.githubusercontent.com/73111474/126005307-c74934df-572d-4aad-b986-66dd33cd5e8c.png)
i am getting few erros like that.
how can i solve it?
i done everything like the toturial. and its getting the world to load really slow.

**Comment by Foreheadchann** [comment]
Sometimes worlds can be incompatible, and i cannot really fix that
